import { StyleSheet } from "react-native";

export const loginStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: "transparent",
    padding: 24,
    justifyContent: "center",
  },
  header: { alignItems: "center", marginBottom: 40 },
  emoji: { fontSize: 56, marginBottom: 12 },
  title: {
    fontSize: 34,
    fontWeight: "800",
    color: "#335423",
    fontFamily: "Brush Script MT",
  },
  subtitle: { fontSize: 16, color: "#718096", marginTop: 4 },
  form: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  button: { marginTop: 8, backgroundColor: "#2b6227" },
  footer: { flexDirection: "row", justifyContent: "center", marginTop: 24 },
  footerText: { fontSize: 15, color: "#718096" },
  link: { fontSize: 15, color: "#4F46E5", fontWeight: "700" },
});

export const registerStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: "#e5e9e0",
    padding: 24,
    justifyContent: "center",
  },
  header: { alignItems: "center", marginBottom: 40 },
  emoji: { fontSize: 56, marginBottom: 12 },
  title: {
    fontSize: 34,
    fontWeight: "800",
    color: "#335423",
    fontFamily: "Brush Script MT",
  },
  subtitle: { fontSize: 16, color: "#718096", marginTop: 4 },
  form: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  button: { marginTop: 8, backgroundColor: "#2b6227" },
  footer: { flexDirection: "row", justifyContent: "center", marginTop: 24 },
  footerText: { fontSize: 15, color: "#718096" },
  link: { fontSize: 15, color: "#4F46E5", fontWeight: "700" },
});

export const homeStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: "rgba(255, 255, 255, 0.35)",
    padding: 24,
    paddingTop: 72,
  },
  logoCenter: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 28,
  },
  subtitle: {
    fontSize: 16,
    color: "#718096",
    marginTop: 4,
    textAlign: "center",
  },
  heroCard: {
    minHeight: 124,
    backgroundColor: "rgba(223, 237, 215, 0.92)",
    borderRadius: 18,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
borderWidth: 1,
  borderColor: "rgba(111, 166, 106, 0.35)",

    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  heroText: { flex: 1 },
  greeting: { fontSize: 33, fontWeight: "800", color: "#335423" },
  email: { fontSize: 13, color: "#3A4A3D", marginTop: 4, lineHeight: 19 },
  logoutBtn: {
    position: "absolute",
    top: 45,
    right: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFF5F5",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#F2CACA",
  },
  logoutText: { color: "#C94C4C", fontSize: 14, fontWeight: "700" },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 28,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#236B2E",
    marginLeft: 10,
  },
  actionCard: {
    minHeight: 116,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderRadius: 18,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  primaryAction: {
    backgroundColor: "rgba(255, 255, 255, 0.92)",
  },
  actionIconPrimary: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: "#E8F6DD",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 18,
  },
  actionIconSecondary: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: "#E8F6DD",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 18,
  },
  actionText: { flex: 1 },
  actionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1e6329",
    marginBottom: 4,
  },
  actionDescription: {
    fontSize: 13,
    color: "#31423A",
    lineHeight: 18,
  },
});

export const loadingStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#dae9de",
  },
  text: { marginTop: 12, fontSize: 16, color: "#718096" },
});

export const cameraStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0F1F13",
  },
  centerContent: {
    flex: 1,
    backgroundColor: "#E5E9E0",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  title: {
    fontSize: 22,
    fontWeight: "800",
    color: "#335423",
    textAlign: "center",
    marginTop: 12,
  },
  message: {
    fontSize: 15,
    color: "#3A4A3D",
    textAlign: "center",
    lineHeight: 22,
    marginTop: 8,
  },
  camera: {
    flex: 1,
  },
  cameraTopBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingTop: 54,
    paddingHorizontal: 20,
    alignItems: "flex-end",
  },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    justifyContent: "center",
    alignItems: "center",
  },
  cameraFooter: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    padding: 24,
    paddingBottom: 40,
    backgroundColor: "rgba(0, 0, 0, 0.28)",
  },
  cameraHint: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 18,
    textAlign: "center",
  },
  captureButton: {
    width: 78,
    height: 78,
    borderRadius: 39,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 4,
    borderColor: "rgba(255, 255, 255, 0.55)",
  },
  captureButtonInner: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#236B2E",
  },
  preview: {
    flex: 1,
    width: "100%",
  },
  previewPanel: {
    backgroundColor: "#FFFFFF",
    padding: 24,
    paddingBottom: 42,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  primaryButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 12,
    backgroundColor: "#236B2E",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
  },
  secondaryButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 12,
    backgroundColor: "#E8F6DD",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  secondaryButtonText: {
    color: "#236B2E",
    fontSize: 15,
    fontWeight: "800",
  },
});

export const scanResultStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: "rgba(255, 255, 255, 0.5)",
    padding: 24,
    paddingTop: 72,
  },
  backButton: {
    position: "absolute",
    top: 44,
    left: 24,
    width: 54,
    height: 54,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    zIndex: 2,
  },
  header: {
    alignItems: "center",
    marginBottom: 24,
  },
  title: {
    fontSize: 34,
    fontWeight: "800",
    color: "#236B2E",
  },
  subtitle: {
    fontSize: 18,
    color: "#2D3748",
    marginTop: 6,
    textAlign: "center",
  },
  summaryCard: {
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    borderRadius: 20,
    padding: 14,
    flexDirection: "row",
    gap: 14,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  photo: {
    width: 128,
    height: 128,
    borderRadius: 14,
    backgroundColor: "#E2E8F0",
  },
  summaryInfo: {
    flex: 1,
    justifyContent: "center",
  },
  label: {
    fontSize: 13,
    fontWeight: "700",
    color: "#2D3748",
    marginBottom: 3,
    textTransform: "uppercase",
  },
  residueName: {
    fontSize: 20,
    fontWeight: "800",
    color: "#236B2E",
    marginBottom: 8,
  },
  badge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 10,
  },
  recyclableBadge: {
    backgroundColor: "#E8F6DD",
  },
  notRecyclableBadge: {
    backgroundColor: "#FEE4E2",
  },
  badgeText: {
    fontSize: 14,
    fontWeight: "800",
  },
  recyclableText: {
    color: "#236B2E",
  },
  notRecyclableText: {
    color: "#B42318",
  },
  description: {
    fontSize: 13,
    color: "#2D3748",
    lineHeight: 18,
  },
  detectedList: {
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    borderRadius: 18,
    padding: 12,
    gap: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  detectedItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  detectedIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#E8F6DD",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  detectedText: {
    flex: 1,
  },
  detectedName: {
    fontSize: 15,
    fontWeight: "800",
    color: "#236B2E",
    marginBottom: 2,
  },
  detectedDescription: {
    fontSize: 12,
    color: "#2D3748",
    lineHeight: 16,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 22,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#236B2E",
    marginLeft: 10,
  },
  recommendationCard: {
    backgroundColor: "rgba(232, 246, 221, 0.94)",
    borderRadius: 18,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  recommendationIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },
  recommendationText: {
    flex: 1,
    fontSize: 14,
    color: "#1F3D2A",
    lineHeight: 20,
    fontWeight: "600",
  },
  infoCard: {
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    borderRadius: 18,
    padding: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 6,
  },
  infoIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#E8F6DD",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  infoText: {
    flex: 1,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#236B2E",
    marginBottom: 3,
  },
  infoDescription: {
    fontSize: 13,
    color: "#2D3748",
    lineHeight: 18,
  },
  divider: {
    height: 1,
    backgroundColor: "#E2E8F0",
    marginVertical: 6,
  },
  primaryButton: {
    minHeight: 58,
    borderRadius: 14,
    backgroundColor: "#236B2E",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    marginTop: 28,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
  },
  secondaryButton: {
    minHeight: 58,
    borderRadius: 14,
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    marginTop: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  secondaryButtonText: {
    color: "#236B2E",
    fontSize: 18,
    fontWeight: "800",
  },
});

export const buttonStyles = StyleSheet.create({
  button: {
    height: 50,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  text: {
    fontSize: 16,
    fontWeight: "600",
  },
});

export const cardStyles = StyleSheet.create({
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
});

export const inputStyles = StyleSheet.create({
  container: { marginBottom: 16 },
  label: { fontSize: 14, fontWeight: "600", color: "#2D3748", marginBottom: 6 },
  inputWrapper: { position: "relative" },
  input: {
    height: 50,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 15,
    color: "#2D3748",
    backgroundColor: "#F7FAFC",
  },
  inputError: { borderColor: "#E53E3E" },
  eyeIcon: { position: "absolute", right: 14, top: 12 },
  eyeText: { fontSize: 20 },
  errorText: { fontSize: 12, color: "#E53E3E", marginTop: 4 },
});
